# Generated by Django 6.0.3 on 2026-04-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orders_orde_custome_c9b64a_idx_and_more'),
        ('restaurants', '0001_initial'),
        ('users', '0002_address_customerprofile_driverprofile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['customer', 'restaurant'], name='orders_revi_custome_e24b7d_idx'),
        ),
    ]
